### ISSUE TITLE
非推奨ライブラリpolyfill.ioについて、置き換えの提案

### ISSUE THREAD

**Issue by yorsh1111** [rinatz/cpp-book#102]
### 概要

本リポジトリでは polyfill.io を使用しています。
polyfill.ioは参考資料に示すように、セキュリティリスクがあり、非推奨です。
別の安全なpolyfillを利用するか、polyfill自体の使用を中止することを提案します。

### 代替となるpolyfill

- https://polyfill-fastly.io
- https://cdnjs.cloudflare.com/polyfill/

### 該当箇所

rootのmkdocs.ymlの58行目

```yml
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
```

### 参考資料

- [Polyfill supply chain attack hits 100K+ sites](https://sansec.io/research/polyfill-supply-chain-attack)
- [polyfill.ioを使うのは危険かもしれない(危険だった)](https://qiita.com/hiroiku/items/6d229b6f2e59f1ce943e)

**Comment by rinatz** [comment]
ありがとうございます。
`extra_javascript` 自体を削除しても大丈夫なので、削除します。
