### ISSUE TITLE
POD 型の説明がほしい

### ISSUE THREAD

**Issue by rinatz** [rinatz/cpp-book#40]
構造体とクラスの違いを理解してない人をよく見るので
POD 型の説明も含めてほしいです。

構造体は POD 型の場合のみメモリレイアウトも C 互換になる（memset() が使える）
POD 型じゃないとクラスとしてコンパイルされる（memset() が使えない）

**Comment by km45** [comment]
POD かどうかの判定は type_traits の機能で判定できるので static_assert を使えばよい。
https://cpprefjp.github.io/reference/type_traits/is_pod.html

POD の詳しい要件ではなく、
POD にすることで memset などのメモリ操作が可能になることや実際の使い方を説明する。
