### ISSUE TITLE
結局関数オブジェクトとはなんなのか

### ISSUE THREAD

**Issue by yumetodo** [rinatz/cpp-book#52]
https://rinatz.github.io/cpp-book/ch02-09-function-objects/

いきなりラムダ式の解説が出てくるのはいいとして、関数オブジェクトの解説ページのはずなのに、どこにも説明が存在しない。

**Comment by rinatz** [comment]
@km45 @cpmrph 
このページに関数オブジェクトの説明がない理由って何でしょうか？

**Comment by km45** [comment]
@rinatz 
関数オブジェクトの説明がないのは意図したものではなく、記述漏れです。

なお、このページで解説したい関数オブジェクトとは N3337 の [20.8 Function objects][n3337.function.objects] のことです。

[n3337.function.objects]: https://timsong-cpp.github.io/cppwp/n3337/function.objects

**Comment by rinatz** [comment]
タイトルをラムダ式に変えたほうがいいのかしら？

**Comment by yumetodo** [comment]
operator overloadの説明したときに関数オブジェクト取り上げるのが自然かもしれない？

**Comment by km45** [comment]
このページで主に説明したいのは関数ポインタとラムダ式なので `operator()` メンバ関数を持つクラスのオブジェクトなどを含む関数オブジェクトとして取り上げる必要はなさそうです。

関数オブジェクトというタイトルのページなのに説明がない問題については @rinatz さんが提案しているページタイトルの変更で関数オブジェクトという記述を削除するのがいいかと思います。

**Comment by yumetodo** [comment]
その場合はcaptureしてないlambdaは関数ポインタに暗黙変換できることに言及してもいいかもしれませんね。
