### ISSUE TITLE
char は signed char でも unsigned char でもない

### ISSUE THREAD

**Issue by SaitoAtsushi** [rinatz/cpp-book#54]
> `signed` を付けると正負両方の値が表現できます。 明示的に付けなくてもデフォルトは `signed` になります。

`char` は `signed char` ではありません。

**Comment by yohhoy** [comment]
C++では `char`, `signed char`, `unsigned char` はそれぞれ異なる型として定義されています。[[basic.types]/1](https://timsong-cpp.github.io/cppwp/n3337/basic.types#basic.fundamental-1)
> Plain `char`, `signed char`, and `unsigned char` are three distinct types.

プレーンな`char`型が符号付き／符号なしのいずれかは、仕様上は処理系定義(implementation-defined)とされています。
> It is implementation-defined whether a `char` object can hold negative values.

実際にはコンパイラオプションで符号有無を選択できたり、対象プロセッサアーキテクチャによって決まるのが一般的ですね。

**Comment by rinatz** [comment]
Arm 対応の時とかによくバグるやつですね・・・

yohhoy さんの文言をほとんど拝借する形になりますが
下記のように文言を追加するのでいかがでしょう？

```
!!! warning "`char` は `signed char` じゃない？"
    C++ では `char, signed char, unsigned char` はそれぞれ異なる型として定義されています。
    プレーンな `char` 型が符号付き・符号なしのいずれになるかは、仕様上は処理系定義(implementation-defined)とされています。
    実際にはコンパイラオプションで符号有無を選択できたり、対象プロセッサアーキテクチャによって決まるのが一般的です。
    移植性のあるコードを書く場合は十分注意して下さい。
```

**Comment by yohhoy** [comment]
サイト趣旨をこえたExtra情報になってしまうかもしれませんが、少しだけ改善提案です。採用はお任せします。
* 「C++では」 → 「C言語やC++では」（Cでも`char`/`signed char`/`signed char`は別の型；[JPCERT INT07-C](https://www.jpcert.or.jp/sc-rules/c-int07-c.html)）
* 「対象プロセッサアーキテクチャによって」→「対象プロセッサアーキテクチャなどから」（例えば[GCCではABI依存](https://gcc.gnu.org/onlinedocs/gcc/Characters-implementation.html)；少々ぼかした表現に）

**Comment by rinatz** [comment]
ありがとうございます！

それでは上記の補足＋微修正を加えて下記の文言で修正いたします。

```
!!! warning "`char` は `signed char` じゃない？"
    C++ では `char, signed char, unsigned char` はそれぞれ異なる型として定義されています（C言語も同様です）。
    プレーンな `char` 型が符号付き・符号なしのいずれになるかは、仕様上は処理系定義(implementation-defined)とされています。
    実際にはコンパイラオプションで符号有無を選択できたり、対象プロセッサアーキテクチャなどから決まるのが一般的です。
    移植性のあるコードを書く場合は十分注意して下さい。
```
