### ISSUE TITLE
範囲for文の挙動

### ISSUE THREAD

**Issue by SaitoAtsushi** [rinatz/cpp-book#74]
> 以下のように書いた場合と同じ挙動になります。
>
> ```cpp
> std::vector<int> x = {0, 1, 2, 3, 4};
> 
> for (auto it = x.begin(); it != x.end(); ++it) {
>     std::cout << *it << std::endl;
> }
> ```

[`end` はループ開始前に一度しか呼ばれません](https://timsong-cpp.github.io/cppwp/n3337/stmt.ranged#1)。

この例に限った見かけ上の挙動という意味では同じと言えなくもないですが、正確さに欠けるように思われます。

**Comment by yohhoy** [comment]
C++11以降も範囲for文の挙動はいろいろ改定されています。あまり厳密さにこだわらず「おおむね同じ挙動になる」と説明する案はいかがでしょう？

- C++17: [範囲forループの制限緩和](https://cpprefjp.github.io/lang/cpp17/generalizing_the_range-based_for_loop.html)（begin/endで異なる型を許容）
- C++20: [範囲for文がカスタマイゼーションポイントを見つけるルールを緩和](https://cpprefjp.github.io/lang/cpp20/relaxing_the_range_for_loop_customization_point_finding_rules.html)

**Comment by rinatz** [comment]
イテレータを使った for 文と範囲 for 文の記述順を逆にしてみるのはどうでしょうか？

---

イテレータを使ったコンテナのループ

```cpp
std::vector<int> x = {0, 1, 2, 3, 4};

for (auto it = x.begin(); it != x.end(); ++it) {
    std::cout << *it << std::endl;
}
```

は範囲 for 文という構文を使って下記のように、よりシンプルに書くことが出来ます。

```cpp
for (const auto e : x) {
    std::cout << e << std::endl;
}
```
