### ISSUE TITLE
override キーワードの効果

### ISSUE THREAD

**Issue by SaitoAtsushi** [rinatz/cpp-book#82]
> オーバーライドするには派生クラスのメンバ関数に `override` をつけます。

もちろん習慣としては常につけたほうが良いのですが、オーバーライドになるかどうかは[同じ名前・同じシグネチャであること](https://timsong-cpp.github.io/cppwp/n3337/class.virtual#2)がまず基準として有るのでその説明は必要ではないでしょうか。

`override` キーワードは[オーバーライドになってないときに不正ということにする](https://timsong-cpp.github.io/cppwp/n3337/class.virtual#5)という補助的な機能しかもちませんが、今の説明だと  `override` キーワードを付けることでオーバーライドになるというように読めてしまいます。

**Comment by yohhoy** [comment]
修正素案です：

派生クラスで仮想関数の挙動を変更することをオーバーライドといいます。 派生クラスでオーバライドを行うには、仮想関数シグニチャ（引数の型や`const`修飾の有無）を厳密一致させる必要があります。オーバーライドであることを明確化するため派生クラスのメンバ関数に `override` 明示が推奨されます。

----
`override` は「プログラマのミスや基底クラスの仕様変更により、関数シグニチャが厳密一致しないためオーバーライドに失敗する」事故を防ぐために導入された仕組みです。[このような導入経緯](https://cpprefjp.github.io/lang/cpp11/override_final.html)に参考言及してもよいかもしれませんね。
