### ISSUE TITLE
3.1. 配列 中の誤記について

### ISSUE THREAD

**Issue by tookunozima** [rinatz/cpp-book#92]
githubについて慣れてなく、Issuesに提起してよいのか分かりませんが、

[配列の要素数を求める方法としてC++11より前ではプリプロセッサマクロを使用するのが一般的でしたが、C++11からは次のようにして求めることができます。この関数はC++17以降では `std:size` という関数として標準ライブラリに存在します。](https://github.com/rinatz/cpp-book/blob/aed44113325ef1b22d3301dd9571478c373e06bf/docs/ch03-01-arrays.md?plain=1#LL129C93-L129C101)

の'std:size'という部分は'std::size'関数と解してよろしいでしょうか。
貴サイトにてC++勉強中です。よろしくお願いいたします。

**Comment by yumetodo** [comment]
あ・・・。
PR投げました

**Comment by tookunozima** [comment]
ありがとうございます。

**Comment by tookunozima** [comment]
ありがとうございます。
